trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "Verificando conectividad con el servidor Tosca..."
    curl -k -v https://10.192.221.33
  displayName: Verificar conectividad con Tosca Server
