trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "Verificando conectividad con el servidor Tosca..."
    curl -k -v https://CLSCLTRICOSPRD.arauco.cl
  displayName: Verificar conectividad con Tosca Server
