trigger: none

pool:
  name: 'CLSCLDEVOPSLNX2'  

steps:
  - script: |
      echo "Step 1: Obtener Token de Autenticación"

      RESPONSE=$(curl -s -X POST "$(TOSCA_URL)/tua/connect/token" \
        -H "Content-Type: application/x-www-form-urlencoded" \
        -d "grant_type=client_credentials" \
        -d "client_id=$(CLIENT_ID)" \
        -d "client_secret=$(CLIENT_SECRET)")

      echo "Respuesta recibida: $RESPONSE"

      TOKEN=$(echo $RESPONSE | jq -r '.access_token')

      if [[ -z "$TOKEN" || "$TOKEN" == "null" ]]; then
        echo "Error: No se pudo obtener el token."
        exit 1
      fi
      echo "Token:  $TOKEN"

  - script: |
      echo "Step 2: Ejecutar Automación en Tosca"
      echo "Token:  $TOKEN"

      EXECUTION_RESPONSE=$(curl -s -X POST "$(TOSCA_URL)/automationobjectservice/api/Execution/Enqueue" \
        -H "Authorization: Bearer $TOKEN" \
        -H "X-Tricentis: OK" \
        -H "Content-Type: application/json" \
        -d '{
          "projectName": "$(PROJECT_NAME)",
          "executionEnvironment": "$(EXECUTION_ENV)",
          "events": [
            {
              "eventId": "$(EVENT_ID)",
              "parameters": {},
              "characteristics": {}
            }
          ],
          "importResult": true,
          "creator": "$(CREATOR)"
        }' -k -v)

      echo "Respuesta de la ejecución: $EXECUTION_RESPONSE"
