trigger: none

pool:
  name: 'CLSCLDEVOPSLNX2'

steps:
- script: |
    echo "Verificando conectividad con el servidor Tosca..."
    curl --location 'https://certificaciontosca.arauco.com/tua/connect/token' \
      --header 'Content-Type: application/x-www-form-urlencoded' \
      --data-urlencode 'grant_type=client_credentials' \
      --data-urlencode 'client_id=hSw__vACjU6VXjUOPjHf6Q' \
      --data-urlencode 'client_secret=iPAlqwjlrEGXqHrCY8RZrQOS2CpEL1eUWiNC9ORxlsPw' -k -v
  displayName: Verificar conectividad con Tosca Server
